{
  "id": "GHSA-5xc6-fpc7-4qvg",
  "summary": "CoAPthon DoS due to Exceptions",
  "details": "The `Serialize.deserialize()` method in CoAPthon 3.1, 4.0.0, 4.0.1, and 4.0.2 mishandles certain exceptions, leading to a denial of service in applications that use this library (e.g., the standard CoAP server, CoAP client, CoAP reverse proxy, example collect CoAP server and client) when they receive crafted CoAP messages.",
  "aliases": [
    "CVE-2018-12680",
    "PYSEC-2019-165"
  ],
  "modified": "2024-02-16T08:24:59.284864Z",
  "published": "2019-04-08T15:19:01Z",
  "database_specific": {
    "nvd_published_at": null,
    "cwe_ids": [
      "CWE-400",
      "CWE-502"
    ],
    "severity": "HIGH",
    "github_reviewed": true,
    "github_reviewed_at": "2020-06-16T21:17:34Z"
  },
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2018-12680"
    },
    {
      "type": "WEB",
      "url": "https://github.com/Tanganelli/CoAPthon/issues/135"
    },
    {
      "type": "PACKAGE",
      "url": "https://github.com/Tanganelli/CoAPthon"
    },
    {
      "type": "ADVISORY",
      "url": "https://github.com/advisories/GHSA-5xc6-fpc7-4qvg"
    }
  ],
  "affected": [
    {
      "package": {
        "name": "coapthon",
        "ecosystem": "PyPI",
        "purl": "pkg:pypi/coapthon"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "last_affected": "4.0.2"
            }
          ]
        }
      ],
      "versions": [
        "4.0.0",
        "4.0.1",
        "4.0.2"
      ],
      "database_specific": {
        "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2019/04/GHSA-5xc6-fpc7-4qvg/GHSA-5xc6-fpc7-4qvg.json"
      }
    }
  ],
  "schema_version": "1.6.0",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
    }
  ]
}