{
  "id": "MAL-2024-4775",
  "summary": "Malicious code in args-python (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "aliases": [
    "SNYK-PYTHON-ARGSPYTHON-5591088"
  ],
  "modified": "2024-06-28T03:14:45.269434Z",
  "published": "2024-06-25T13:32:28Z",
  "database_specific": {
    "malicious-packages-origins": [
      {
        "modified_time": "2024-06-25T13:32:28Z",
        "import_time": "2024-06-28T02:48:17.065670703Z",
        "versions": [
          "12.4.5",
          "12.5.5"
        ],
        "id": "RLMA-2024-03555",
        "source": "reversing-labs",
        "sha256": "98e3c2618a36d29a675de35b1d681d843c7eb7aa6afaeca5d09e62c9b290729a"
      }
    ]
  },
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://security.snyk.io/vuln/SNYK-PYTHON-ARGSPYTHON-5591088"
    },
    {
      "type": "ARTICLE",
      "url": "https://medium.com/checkmarx-security/pypi-on-hold-suspends-new-users-and-projects-creations-due-to-a-high-volume-of-malicious-activity-7ff09cd25f3e"
    }
  ],
  "affected": [
    {
      "package": {
        "name": "args-python",
        "ecosystem": "PyPI",
        "purl": "pkg:pypi/args-python"
      },
      "versions": [
        "12.4.5",
        "12.5.5"
      ],
      "database_specific": {
        "source": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/args-python/MAL-2024-4775.json"
      }
    }
  ],
  "schema_version": "1.6.0",
  "credits": [
    {
      "name": "ReversingLabs",
      "contact": [
        "https://www.reversinglabs.com"
      ],
      "type": "FINDER"
    }
  ]
}