{
  "id": "MAL-2024-5590",
  "summary": "Malicious code in py-cocd (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "aliases": [
    "SNYK-PYTHON-PYCOCD-6513230"
  ],
  "modified": "2024-06-28T03:15:02.609541Z",
  "published": "2024-06-25T13:39:03Z",
  "database_specific": {
    "malicious-packages-origins": [
      {
        "modified_time": "2024-06-25T13:39:03Z",
        "import_time": "2024-06-28T02:49:52.543517818Z",
        "versions": [
          "1.0.0"
        ],
        "id": "RLMA-2024-04372",
        "source": "reversing-labs",
        "sha256": "18d3d4182bde90e41296603be8800566a7e5f69a0d12b383cdb3192b74a99022"
      }
    ]
  },
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://security.snyk.io/vuln/SNYK-PYTHON-PYCOCD-6513230"
    },
    {
      "type": "ARTICLE",
      "url": "https://medium.com/checkmarx-security/pypi-is-under-attack-project-creation-and-user-registration-suspended-heres-the-details-c3b6291d4579"
    }
  ],
  "affected": [
    {
      "package": {
        "name": "py-cocd",
        "ecosystem": "PyPI",
        "purl": "pkg:pypi/py-cocd"
      },
      "versions": [
        "1.0.0"
      ],
      "database_specific": {
        "source": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/py-cocd/MAL-2024-5590.json"
      }
    }
  ],
  "schema_version": "1.6.0",
  "credits": [
    {
      "name": "ReversingLabs",
      "contact": [
        "https://www.reversinglabs.com"
      ],
      "type": "FINDER"
    }
  ]
}