{
  "id": "MAL-2024-4867",
  "summary": "Malicious code in capmonstercloudclouidclient (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "aliases": [
    "SNYK-PYTHON-CAPMONSTERCLOUDCLOUIDCLIENT-6513542"
  ],
  "modified": "2024-06-28T03:14:48.512963Z",
  "published": "2024-06-25T13:33:13Z",
  "database_specific": {
    "malicious-packages-origins": [
      {
        "modified_time": "2024-06-25T13:33:13Z",
        "import_time": "2024-06-28T02:48:27.35113073Z",
        "versions": [
          "1.0.0"
        ],
        "id": "RLMA-2024-03647",
        "source": "reversing-labs",
        "sha256": "e6111372e5ca2b9a9bd73c0e1eda272b0101e49f14086a520f238201f2525a78"
      }
    ]
  },
  "references": [
    {
      "type": "ARTICLE",
      "url": "https://medium.com/checkmarx-security/pypi-is-under-attack-project-creation-and-user-registration-suspended-heres-the-details-c3b6291d4579"
    },
    {
      "type": "ADVISORY",
      "url": "https://security.snyk.io/vuln/SNYK-PYTHON-CAPMONSTERCLOUDCLOUIDCLIENT-6513542"
    }
  ],
  "affected": [
    {
      "package": {
        "name": "capmonstercloudclouidclient",
        "ecosystem": "PyPI",
        "purl": "pkg:pypi/capmonstercloudclouidclient"
      },
      "versions": [
        "1.0.0"
      ],
      "database_specific": {
        "source": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/capmonstercloudclouidclient/MAL-2024-4867.json"
      }
    }
  ],
  "schema_version": "1.6.0",
  "credits": [
    {
      "name": "ReversingLabs",
      "contact": [
        "https://www.reversinglabs.com"
      ],
      "type": "FINDER"
    }
  ]
}