{
  "id": "MAL-2024-5933",
  "summary": "Malicious code in requxsts (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "aliases": [
    "SNYK-PYTHON-REQUXSTS-6513390"
  ],
  "modified": "2024-06-28T03:15:15.425064Z",
  "published": "2024-06-25T13:41:57Z",
  "database_specific": {
    "malicious-packages-origins": [
      {
        "modified_time": "2024-06-25T13:41:57Z",
        "import_time": "2024-06-28T02:50:35.753610925Z",
        "versions": [
          "1.0.0"
        ],
        "id": "RLMA-2024-04734",
        "source": "reversing-labs",
        "sha256": "a9d6dbdd361b0b0fb84e7ed99779dba2ce27149d60d11d6af1b5ecc9ab7e1eab"
      }
    ]
  },
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://security.snyk.io/vuln/SNYK-PYTHON-REQUXSTS-6513390"
    },
    {
      "type": "ARTICLE",
      "url": "https://medium.com/checkmarx-security/pypi-is-under-attack-project-creation-and-user-registration-suspended-heres-the-details-c3b6291d4579"
    }
  ],
  "affected": [
    {
      "package": {
        "name": "requxsts",
        "ecosystem": "PyPI",
        "purl": "pkg:pypi/requxsts"
      },
      "versions": [
        "1.0.0"
      ],
      "database_specific": {
        "source": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/requxsts/MAL-2024-5933.json"
      }
    }
  ],
  "schema_version": "1.6.0",
  "credits": [
    {
      "name": "ReversingLabs",
      "contact": [
        "https://www.reversinglabs.com"
      ],
      "type": "FINDER"
    }
  ]
}