{
  "id": "MAL-2024-4840",
  "summary": "Malicious code in bup-utils (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "aliases": [
    "SNYK-PYTHON-BUPUTILS-6513304"
  ],
  "modified": "2024-06-28T03:14:47.179497Z",
  "published": "2024-06-25T13:33:00Z",
  "database_specific": {
    "malicious-packages-origins": [
      {
        "modified_time": "2024-06-25T13:33:00Z",
        "import_time": "2024-06-28T02:48:24.279780775Z",
        "versions": [
          "1.0.0"
        ],
        "id": "RLMA-2024-03620",
        "source": "reversing-labs",
        "sha256": "4b4ddaf2798e06f430bf4fedc66197443da7354bb6e92983abb3392a57e7f27c"
      }
    ]
  },
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://security.snyk.io/vuln/SNYK-PYTHON-BUPUTILS-6513304"
    },
    {
      "type": "ARTICLE",
      "url": "https://medium.com/checkmarx-security/pypi-is-under-attack-project-creation-and-user-registration-suspended-heres-the-details-c3b6291d4579"
    }
  ],
  "affected": [
    {
      "package": {
        "name": "bup-utils",
        "ecosystem": "PyPI",
        "purl": "pkg:pypi/bup-utils"
      },
      "versions": [
        "1.0.0"
      ],
      "database_specific": {
        "source": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/bup-utils/MAL-2024-4840.json"
      }
    }
  ],
  "schema_version": "1.6.0",
  "credits": [
    {
      "name": "ReversingLabs",
      "contact": [
        "https://www.reversinglabs.com"
      ],
      "type": "FINDER"
    }
  ]
}