{
  "id": "MAL-2024-5622",
  "summary": "Malicious code in py-cowrd (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "aliases": [
    "SNYK-PYTHON-PYCOWRD-6513663"
  ],
  "modified": "2024-06-28T03:15:05.368925Z",
  "published": "2024-06-25T13:39:18Z",
  "database_specific": {
    "malicious-packages-origins": [
      {
        "modified_time": "2024-06-25T13:39:18Z",
        "import_time": "2024-06-28T02:49:56.321526825Z",
        "versions": [
          "1.0.0"
        ],
        "id": "RLMA-2024-04404",
        "source": "reversing-labs",
        "sha256": "0ca0de2d13f4f5750a9f8e90fbcf1f6312057d490ce94ce0ebd8c764aec9e1cc"
      }
    ]
  },
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://security.snyk.io/vuln/SNYK-PYTHON-PYCOWRD-6513663"
    },
    {
      "type": "ARTICLE",
      "url": "https://medium.com/checkmarx-security/pypi-is-under-attack-project-creation-and-user-registration-suspended-heres-the-details-c3b6291d4579"
    }
  ],
  "affected": [
    {
      "package": {
        "name": "py-cowrd",
        "ecosystem": "PyPI",
        "purl": "pkg:pypi/py-cowrd"
      },
      "versions": [
        "1.0.0"
      ],
      "database_specific": {
        "source": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/py-cowrd/MAL-2024-5622.json"
      }
    }
  ],
  "schema_version": "1.6.0",
  "credits": [
    {
      "name": "ReversingLabs",
      "contact": [
        "https://www.reversinglabs.com"
      ],
      "type": "FINDER"
    }
  ]
}