{
  "id": "MAL-2024-5877",
  "summary": "Malicious code in requekts (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "aliases": [
    "SNYK-PYTHON-REQUEKTS-6513652"
  ],
  "modified": "2024-06-28T03:15:13.349922Z",
  "published": "2024-06-25T13:41:31Z",
  "database_specific": {
    "malicious-packages-origins": [
      {
        "modified_time": "2024-06-25T13:41:31Z",
        "import_time": "2024-06-28T02:50:28.754102529Z",
        "versions": [
          "1.0.0"
        ],
        "id": "RLMA-2024-04678",
        "source": "reversing-labs",
        "sha256": "ffc2fea2627a35555ffaff831a9f9432bcd8d40274cf2f05813009174fed777f"
      }
    ]
  },
  "references": [
    {
      "type": "ARTICLE",
      "url": "https://medium.com/checkmarx-security/pypi-is-under-attack-project-creation-and-user-registration-suspended-heres-the-details-c3b6291d4579"
    },
    {
      "type": "ADVISORY",
      "url": "https://security.snyk.io/vuln/SNYK-PYTHON-REQUEKTS-6513652"
    }
  ],
  "affected": [
    {
      "package": {
        "name": "requekts",
        "ecosystem": "PyPI",
        "purl": "pkg:pypi/requekts"
      },
      "versions": [
        "1.0.0"
      ],
      "database_specific": {
        "source": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/requekts/MAL-2024-5877.json"
      }
    }
  ],
  "schema_version": "1.6.0",
  "credits": [
    {
      "name": "ReversingLabs",
      "contact": [
        "https://www.reversinglabs.com"
      ],
      "type": "FINDER"
    }
  ]
}