{
  "id": "MAL-2024-5813",
  "summary": "Malicious code in pythoncryptov4 (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "aliases": [
    "SNYK-PYTHON-PYTHONCRYPTOV4-5932266"
  ],
  "modified": "2024-06-28T03:15:11.115467Z",
  "published": "2024-06-25T13:40:59Z",
  "database_specific": {
    "malicious-packages-origins": [
      {
        "modified_time": "2024-06-25T13:40:59Z",
        "import_time": "2024-06-28T02:50:20.718992404Z",
        "versions": [
          "1.0.0"
        ],
        "id": "RLMA-2024-04611",
        "source": "reversing-labs",
        "sha256": "380b8d95a61cea6dabfb724a8333eee3ae3128b1e46d99f258ce0dbf5b8e9103"
      }
    ]
  },
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://security.snyk.io/vuln/SNYK-PYTHON-PYTHONCRYPTOV4-5932266"
    },
    {
      "type": "ARTICLE",
      "url": "https://medium.com/checkmarx-security/the-evolutionary-tale-of-a-persistent-python-threat-d19196d4ed15"
    }
  ],
  "affected": [
    {
      "package": {
        "name": "pythoncryptov4",
        "ecosystem": "PyPI",
        "purl": "pkg:pypi/pythoncryptov4"
      },
      "versions": [
        "1.0.0"
      ],
      "database_specific": {
        "source": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/pythoncryptov4/MAL-2024-5813.json"
      }
    }
  ],
  "schema_version": "1.6.0",
  "credits": [
    {
      "name": "ReversingLabs",
      "contact": [
        "https://www.reversinglabs.com"
      ],
      "type": "FINDER"
    }
  ]
}